version: '3'
services:
  ui:
    build: ./ui
    command: 'npm run serve'
    ports:
      - '${VUE_APP_UI_PORT}:${VUE_APP_UI_PORT}'
    volumes:
      - './ui:/usr/src/app/ui'
      - '/usr/src/app/ui/node_modules'
    env_file:
      - '.env'
  server:
    build: ./server
    command: 'npm run serve'
    ports:
      - '${VUE_APP_SERVER_PORT}:${VUE_APP_SERVER_PORT}'
    volumes:
      - './server:/usr/src/app/server'
      - '/usr/src/app/server/node_modules'
      - './server/assets:/usr/src/app/server/assets'
    env_file: 
      - '.env'
