version: "3"
services:
  app:
    build: ./app
    command: "npm run serve"
    ports:
      - "${VUE_APP_UI_PORT}:${VUE_APP_UI_PORT}"
    volumes:
      - "./app:/usr/src/app"
      - "/usr/src/app/node_modules"
    env_file:
      - ".env"
  server:
    build: ./server
    command: "npm run serve"
    ports:
      - "${VUE_APP_SERVER_PORT}:${VUE_APP_SERVER_PORT}"
    volumes:
      - "./server:/usr/src/server"
      - "/usr/src/server/node_modules"
    env_file:
      - ".env"
  paged:
    build: ./paged
    privileged: true
    command: "python3 app.py"
    ports:
      - "5001:5001"
    volumes:
      - "./paged:/usr/src/paged"
      - "./server:/usr/src/server"
