# Copyright 2020, Battelle Energy Alliance, LLC  ALL RIGHTS RESERVED

version: '3'
services:
  ui:
    build: ./ui
    command: 'npm run serve'
    ports:
      - '8081:8081'
    volumes:
      - './ui:/usr/src/app/ui'
      - '/usr/src/app/ui/node_modules'
    env_file:
      - './ui/.env'
  adapter:
    build: ./server
    command: 'npm run serve'
    ports:
      - '3001:3001'
    volumes:
      - './server:/usr/src/app/server'
      - '/usr/src/app/server/node_modules'
    env_file: 
      - './server/.env'