# Copyright 2020, Battelle Energy Alliance, LLC  ALL RIGHTS RESERVED

version: '3'
services:
  ui:
    build: ./ui
    command: 'npm run serve'
    ports:
      - '${VUE_APP_UI_PORT}:${VUE_APP_UI_PORT}'
    volumes:
      - './ui:/usr/src/app/ui'
      - '/usr/src/app/ui/node_modules'
    env_file:
      - '.env'
  adapter:
    build: ./server
    command: 'npm run serve'
    ports:
      - '${VUE_APP_SERVER_PORT}:${VUE_APP_SERVER_PORT}'
    volumes:
      - './server:/usr/src/app/server'
      - '/usr/src/app/server/node_modules'
    env_file: 
      - '.env'