# Copyright 2020, Battelle Energy Alliance, LLC  ALL RIGHTS RESERVED

version: '3'
services:
  postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: tracer
      POSTGRES_DB: traces
      POSTGRES_HOST_AUTH_METHOD: "trust"
  server:
    build: ./server
    command: 'npm run serve'
    ports:
      - '${VUE_APP_SERVER_PORT}:${VUE_APP_SERVER_PORT}'
    depends_on:
      - 'postgres'
    volumes:
      - './server:/usr/src/app/server'
      - '/usr/src/app/server/node_modules'
    env_file:
      - '.env'
  ui:
    build: ./ui
    command: 'npm run serve'
    ports:
      - '${VUE_APP_UI_PORT}:${VUE_APP_UI_PORT}'
    depends_on:
      - 'server'
    volumes:
      - './ui:/usr/src/app/ui'
      - '/usr/src/app/ui/node_modules'
    env_file:
      - '.env'
